/**
 * Markdown Converter
 *
 * Converts data to human-readable Markdown format.
 * Ideal for documentation, sharing, and archiving.
 */

import { ExportOptions, ExportStats, DataProvider } from '../types'

export interface MarkdownOptions {
  includeMetadata: boolean
  includeTOC: boolean
  messageFormat: 'chat' | 'log' | 'narrative'
  codeBlocks: boolean
}

export class MarkdownConverter {
  /**
   * Export data to Markdown format
   */
  async exportData(options: ExportOptions, mdOptions: Partial<MarkdownOptions> = {}): Promise<{
    data: Blob
    stats: ExportStats
  }> {
    const startTime = Date.now()
    const finalOptions: MarkdownOptions = {
      includeMetadata: mdOptions.includeMetadata ?? true,
      includeTOC: mdOptions.includeTOC ?? true,
      messageFormat: mdOptions.messageFormat ?? 'chat',
      codeBlocks: mdOptions.codeBlocks ?? true,
    }

    let markdown = ''
    let stats: ExportStats = {
      conversations: 0,
      messages: 0,
      knowledgeEntries: 0,
      contacts: 0,
      totalSize: 0,
      duration: 0,
    }

    const provider = options.dataProvider

    // Add header
    markdown += this.generateHeader(options)

    // Add table of contents
    if (finalOptions.includeTOC) {
      markdown += this.generateTOC(options)
    }

    // Export based on scope
    if (options.scope === 'all' || options.scope === 'conversations') {
      const { content, stats: convStats } = await this.exportConversations(provider, options.dateRange, finalOptions)
      markdown += content
      stats.conversations = convStats.conversations
      stats.messages = convStats.messages
    }

    if (options.scope === 'all' || options.scope === 'knowledge') {
      const { content, stats: knowledgeStats } = await this.exportKnowledge(provider, options.dateRange)
      markdown += content
      stats.knowledgeEntries = knowledgeStats.entries
    }

    if (options.scope === 'all' || options.scope === 'contacts') {
      const { content, stats: contactStats } = await this.exportContacts(provider)
      markdown += content
      stats.contacts = contactStats.contacts
    }

    // Add footer
    markdown += this.generateFooter()

    // Create blob
    const encoder = new TextEncoder()
    const bytes = encoder.encode(markdown)
    stats.totalSize = bytes.length
    stats.duration = Date.now() - startTime

    const blob = new Blob([bytes], { type: 'text/markdown' })

    return { data: blob, stats }
  }

  /**
   * Generate document header
   */
  private generateHeader(options: ExportOptions): string {
    const date = new Date().toLocaleDateString()
    return `# Data Export

**Export Date:** ${date}
**Scope:** ${options.scope}

---

`
  }

  /**
   * Generate table of contents
   */
  private generateTOC(options: ExportOptions): string {
    let toc = '## Table of Contents\n\n'

    if (options.scope === 'all' || options.scope === 'conversations') {
      toc += '- [Conversations](#conversations)\n'
    }

    if (options.scope === 'all' || options.scope === 'knowledge') {
      toc += '- [Knowledge Base](#knowledge-base)\n'
    }

    if (options.scope === 'all' || options.scope === 'contacts') {
      toc += '- [Contacts](#contacts)\n'
    }

    return toc + '\n---\n\n'
  }

  /**
   * Generate document footer
   */
  private generateFooter(): string {
    return `\n---\n\n*Generated by Universal Import/Export v1.0.0*\n`
  }

  /**
   * Export conversations to Markdown
   */
  private async exportConversations(
    provider: DataProvider | undefined,
    dateRange: { start: Date; end: Date } | undefined,
    options: MarkdownOptions
  ): Promise<{ content: string; stats: { conversations: number; messages: number } }> {
    const conversations = provider?.getConversations ? await provider.getConversations() : []
    let markdown = '## Conversations\n\n'
    let messageCount = 0

    for (const conv of conversations) {
      // Apply date range filter
      if (dateRange) {
        const convDate = new Date(conv.createdAt)
        if (convDate < dateRange.start || convDate > dateRange.end) {
          continue
        }
      }

      // Get messages
      const messages = provider?.getMessages ? await provider.getMessages(conv.id) : conv.messages || []
      messageCount += messages.length

      // Add conversation header
      markdown += `### ${this.escapeMarkdown(conv.title || 'Untitled')}\n\n`

      if (options.includeMetadata) {
        markdown += `**Created:** ${new Date(conv.createdAt).toLocaleString()}\n`
        markdown += `**Type:** ${conv.type}\n`
        markdown += `**Messages:** ${messages.length}\n\n`
      }

      // Add messages
      for (const msg of messages) {
        const author = this.getAuthorName(msg.author)
        markdown += `#### ${author}\n\n`

        if (msg.content?.text) {
          markdown += this.escapeMarkdown(msg.content.text) + '\n\n'
        }

        if (options.includeMetadata && msg.timestamp) {
          markdown += `*${new Date(msg.timestamp).toLocaleString()}*\n\n`
        }
      }

      markdown += '---\n\n'
    }

    return {
      content: markdown,
      stats: { conversations: conversations.length, messages: messageCount },
    }
  }

  /**
   * Export knowledge entries to Markdown
   */
  private async exportKnowledge(
    provider: DataProvider | undefined,
    dateRange: { start: Date; end: Date } | undefined
  ): Promise<{ content: string; stats: { entries: number } }> {
    let entries = provider?.getKnowledge ? await provider.getKnowledge() : []

    // Apply date range filter
    if (dateRange) {
      entries = entries.filter((e: any) => {
        const entryDate = new Date(e.timestamp || e.createdAt)
        return entryDate >= dateRange.start && entryDate <= dateRange.end
      })
    }

    let markdown = '## Knowledge Base\n\n'

    for (const entry of entries) {
      markdown += `### ${entry.type?.toUpperCase() || 'ENTRY'}: ${entry.sourceId || entry.id}\n\n`

      if (entry.timestamp) {
        markdown += `**Date:** ${new Date(entry.timestamp).toLocaleString()}\n\n`
      }

      markdown += `${this.escapeMarkdown(entry.content || '')}\n\n`
      markdown += '---\n\n'
    }

    return {
      content: markdown,
      stats: { entries: entries.length },
    }
  }

  /**
   * Export contacts to Markdown
   */
  private async exportContacts(
    provider: DataProvider | undefined
  ): Promise<{ content: string; stats: { contacts: number } }> {
    const contacts = provider?.getContacts ? await provider.getContacts() : []
    let markdown = '## Contacts\n\n'

    for (const contact of contacts) {
      const c = contact as any
      markdown += `### ${this.escapeMarkdown(c.name || c.nickname || 'Contact')}\n\n`

      if (c.createdAt) {
        markdown += `**Created:** ${new Date(contact.createdAt).toLocaleString()}\n\n`
      }

      markdown += '---\n\n'
    }

    return {
      content: markdown,
      stats: { contacts: contacts.length },
    }
  }

  /**
   * Get display name for message author
   */
  private getAuthorName(author: any): string {
    if (author === 'user') return 'You'
    if (typeof author === 'object' && author?.type === 'ai-contact') {
      return author.contactName || 'AI'
    }
    return 'Unknown'
  }

  /**
   * Escape markdown special characters
   */
  private escapeMarkdown(text: string): string {
    return text
      .replace(/\\/g, '\\\\')
      .replace(/\*/g, '\\*')
      .replace(/_/g, '\\_')
      .replace(/\[/g, '\\[')
      .replace(/\]/g, '\\]')
      .replace(/\(/g, '\\(')
      .replace(/\)/g, '\\)')
      .replace(/#/g, '\\#')
      .replace(/\+/g, '\\+')
      .replace(/-/g, '\\-')
      .replace(/\./g, '\\.')
      .replace(/!/g, '\\!')
  }
}
