/**
 * JEPA Markdown Formatter
 *
 * Formats transcripts into clean, readable markdown with proper timestamps,
 * speaker identification, and metadata.
 */

import { Message } from '@/types/conversation'
import {
  JEPA_Transcript,
  MarkdownFormatOptions,
  FormattedTranscript,
  FormatMetadata,
  SpeakerType,
} from '@/types/jepa'
import { formatTimestamp, formatISODate, formatDuration } from './timestamp-formatter'
import { getSpeakerDisplayName, sortSpeakersByPriority, calculateSpeakerStats } from './speaker-detection'

/**
 * Default formatting options
 */
const DEFAULT_FORMAT_OPTIONS: MarkdownFormatOptions = {
  includeTimestamps: true,
  includeSpeakerNames: true,
  includeMetadata: true,
  includeAudioLinks: false,
  timestampFormat: 'hh:mm:ss',
  separator: 'line',
  includeConfidence: false,
}

/**
 * Format a complete transcript into markdown
 * @param transcript - JEPA transcript object
 * @param options - Formatting options
 * @returns Formatted transcript with metadata
 */
export function formatTranscriptToMarkdown(
  transcript: JEPA_Transcript,
  options: Partial<MarkdownFormatOptions> = {}
): FormattedTranscript {
  const opts = { ...DEFAULT_FORMAT_OPTIONS, ...options }

  let markdown = ''

  // Add header with metadata
  if (opts.includeMetadata) {
    markdown += formatTranscriptHeader(transcript)
    markdown += '\n\n'
  }

  // Add transcript body
  markdown += formatTranscriptBody(transcript, opts)

  // Add footer
  markdown += '\n\n---\n'
  markdown += '*Generated by PersonalLog.AI JEPA Transcription*'

  // Calculate format metadata
  const metadata = calculateFormatMetadata(transcript)

  return { markdown, metadata }
}

/**
 * Format messages into markdown (when transcript isn't available yet)
 * @param messages - Array of messages
 * @param sessionId - Session identifier
 * @param options - Formatting options
 * @returns Formatted transcript with metadata
 */
export function formatMessagesToMarkdown(
  messages: Message[],
  sessionId: string,
  options: Partial<MarkdownFormatOptions> = {}
): FormattedTranscript {
  const opts = { ...DEFAULT_FORMAT_OPTIONS, ...options }

  let markdown = ''

  // Add header
  if (opts.includeMetadata) {
    markdown += formatMessagesHeader(messages, sessionId)
    markdown += '\n\n'
  }

  // Add messages body
  markdown += formatMessagesBody(messages, opts)

  // Add footer
  markdown += '\n\n---\n'
  markdown += '*Generated by PersonalLog.AI JEPA Transcription*'

  // Calculate metadata
  const metadata = calculateMessagesMetadata(messages)

  return { markdown, metadata }
}

/**
 * Format transcript header section
 */
function formatTranscriptHeader(transcript: JEPA_Transcript): string {
  const lines: string[] = []

  lines.push('# Enhanced Transcript')
  lines.push(`**Session ID:** ${transcript.sessionId}`)
  lines.push(`**Date:** ${formatISODate(transcript.startedAt, true)}`)

  if (transcript.endedAt) {
    const duration = formatDuration(
      0,
      transcript.duration || 0
    )
    lines.push(`**Duration:** ${duration}`)
  }

  lines.push(`**Speakers:** ${transcript.metadata.totalSpeakers}`)
  lines.push(`**Language:** ${transcript.metadata.language}`)

  if (transcript.metadata.audioUrl && transcript.metadata.audioKept) {
    lines.push(`**Audio:** [Download Recording](${transcript.metadata.audioUrl})`)
  }

  // Speaker list
  if (transcript.metadata.speakers.length > 0) {
    lines.push('\n### Speakers')
    const sortedSpeakers = sortSpeakersByPriority(
      transcript.metadata.speakers.map(s => s.id)
    )

    for (const speakerId of sortedSpeakers) {
      const speaker = transcript.metadata.speakers.find(s => s.id === speakerId)
      if (speaker) {
        const duration = formatDuration(0, speaker.speakingTime)
        lines.push(`- **${speaker.name}**: ${speaker.segmentCount} segments, ${duration}`)
      }
    }
  }

  return lines.join('\n')
}

/**
 * Format messages header section
 */
function formatMessagesHeader(messages: Message[], sessionId: string): string {
  const lines: string[] = []

  lines.push('# Conversation Transcript')
  lines.push(`**Session ID:** ${sessionId}`)
  lines.push(`**Date:** ${formatISODate(new Date().toISOString(), true)}`)
  lines.push(`**Messages:** ${messages.length}`)

  // Calculate speaker stats
  const stats = calculateSpeakerStats(messages)
  if (stats.size > 0) {
    lines.push(`**Speakers:** ${stats.size}`)

    const sortedSpeakers = sortSpeakersByPriority(Array.from(stats.keys()))

    lines.push('\n### Speakers')
    for (const speaker of sortedSpeakers) {
      const speakerStats = stats.get(speaker)!
      const displayName = getSpeakerDisplayName(speaker)
      lines.push(
        `- **${displayName}**: ${speakerStats.messageCount} messages, ${speakerStats.wordCount} words`
      )
    }
  }

  return lines.join('\n')
}

/**
 * Format transcript body with segments
 */
function formatTranscriptBody(
  transcript: JEPA_Transcript,
  options: MarkdownFormatOptions
): string {
  const lines: string[] = []

  lines.push('## Transcript\n')

  for (const segment of transcript.segments) {
    const segmentText = formatSegment(segment, options)
    lines.push(segmentText)

    if (options.separator === 'line') {
      lines.push('')
    } else if (options.separator === 'dash') {
      lines.push('---')
    }
  }

  return lines.join('\n')
}

/**
 * Format messages body
 */
function formatMessagesBody(messages: Message[], options: MarkdownFormatOptions): string {
  const lines: string[] = []

  lines.push('## Transcript\n')

  for (const message of messages) {
    const messageText = formatMessage(message, options)
    lines.push(messageText)

    if (options.separator === 'line') {
      lines.push('')
    } else if (options.separator === 'dash') {
      lines.push('---')
    }
  }

  return lines.join('\n')
}

/**
 * Format a single transcript segment
 */
function formatSegment(
  segment: {
    speaker: SpeakerType
    text: string
    startTime: number
    confidence?: number
  },
  options: MarkdownFormatOptions
): string {
  const lines: string[] = []

  // Timestamp and speaker header
  const timestamp = options.includeTimestamps
    ? `[${formatTimestamp(segment.startTime, options.timestampFormat)}] `
    : ''

  const speaker = options.includeSpeakerNames
    ? getSpeakerDisplayName(segment.speaker)
    : ''

  lines.push(`### ${timestamp}${speaker}`)

  // Text content
  lines.push(segment.text)

  // Confidence if requested
  if (options.includeConfidence && segment.confidence !== undefined) {
    const confidencePercent = Math.round(segment.confidence * 100)
    lines.push(`\n*Confidence: ${confidencePercent}%*`)
  }

  return lines.join('\n')
}

/**
 * Format a single message
 */
function formatMessage(message: Message, options: MarkdownFormatOptions): string {
  const lines: string[] = []

  // Get speaker info from message author
  const authorType =
    message.author === 'user'
      ? 'user'
      : typeof message.author === 'object' && message.author.type === 'ai-contact'
        ? 'assistant'
        : 'system'

  const timestamp = message.timestamp
  const date = new Date(timestamp)
  const seconds = date.getHours() * 3600 + date.getMinutes() * 60 + date.getSeconds()

  // Timestamp and speaker header
  const timeStr = options.includeTimestamps
    ? `[${formatTimestamp(seconds, options.timestampFormat)}] `
    : ''

  const speaker = options.includeSpeakerNames
    ? getSpeakerDisplayName(authorType)
    : ''

  lines.push(`### ${timeStr}${speaker}`)

  // Text content
  const text = message.content.text || ''
  lines.push(text)

  return lines.join('\n')
}

/**
 * Calculate metadata for formatted transcript
 */
function calculateFormatMetadata(transcript: JEPA_Transcript): FormatMetadata {
  let totalWords = 0
  let totalCharacters = 0
  const speakers: SpeakerType[] = []

  for (const segment of transcript.segments) {
    const words = segment.text.split(/\s+/).filter(Boolean).length
    totalWords += words
    totalCharacters += segment.text.length

    if (!speakers.includes(segment.speaker)) {
      speakers.push(segment.speaker)
    }
  }

  const estimatedReadingTime = Math.ceil(totalWords / 200) // 200 words per minute

  return {
    totalSegments: transcript.segments.length,
    totalWords,
    totalCharacters,
    estimatedReadingTime,
    speakers,
    dateRange: {
      start: transcript.startedAt,
      end: transcript.endedAt || transcript.startedAt,
    },
  }
}

/**
 * Calculate metadata for formatted messages
 */
function calculateMessagesMetadata(messages: Message[]): FormatMetadata {
  let totalWords = 0
  let totalCharacters = 0
  const speakers: SpeakerType[] = []

  for (const message of messages) {
    const text = message.content.text || ''
    const words = text.split(/\s+/).filter(Boolean).length
    totalWords += words
    totalCharacters += text.length

    const authorType =
      message.author === 'user'
        ? 'user'
        : typeof message.author === 'object' && message.author.type === 'ai-contact'
          ? 'assistant'
          : 'system'

    if (!speakers.includes(authorType)) {
      speakers.push(authorType)
    }
  }

  const estimatedReadingTime = Math.ceil(totalWords / 200)

  const timestamps = messages.map(m => new Date(m.timestamp).getTime())
  const start = new Date(Math.min(...timestamps)).toISOString()
  const end = new Date(Math.max(...timestamps)).toISOString()

  return {
    totalSegments: messages.length,
    totalWords,
    totalCharacters,
    estimatedReadingTime,
    speakers,
    dateRange: { start, end },
  }
}

/**
 * Export markdown to file (creates download in browser)
 * @param markdown - Markdown content
 * @param filename - Desired filename
 * @returns Promise that resolves when download starts
 */
export async function downloadMarkdownFile(
  markdown: string,
  filename: string = 'transcript.md'
): Promise<void> {
  if (typeof window === 'undefined') {
    throw new Error('downloadMarkdownFile is only available in the browser')
  }

  const blob = new Blob([markdown], { type: 'text/markdown;charset=utf-8' })
  const url = URL.createObjectURL(blob)

  const link = document.createElement('a')
  link.href = url
  link.download = filename
  document.body.appendChild(link)
  link.click()
  document.body.removeChild(link)

  URL.revokeObjectURL(url)
}

/**
 * Copy markdown to clipboard
 * @param markdown - Markdown content
 * @returns Promise that resolves when copied
 */
export async function copyMarkdownToClipboard(markdown: string): Promise<void> {
  if (typeof window === 'undefined') {
    throw new Error('copyMarkdownToClipboard is only available in the browser')
  }

  await navigator.clipboard.writeText(markdown)
}

/**
 * Generate filename for transcript export
 * @param sessionId - Session ID
 * @param date - Date string
 * @param format - File format
 * @returns Generated filename
 */
export function generateTranscriptFilename(
  sessionId: string,
  date: string,
  format: 'md' | 'txt' | 'json' = 'md'
): string {
  const sanitizedSession = sessionId.replace(/[^a-zA-Z0-9-]/g, '_')
  const sanitizedDate = date.replace(/[^a-zA-Z0-9-]/g, '_')
  return `transcript_${sanitizedDate}_${sanitizedSession}.${format}`
}
