/**
 * Feature Flag Data
 *
 * Central registry of all feature flags in PersonalLog.
 * This file is kept separate from types/registry/manager to avoid circular dependencies.
 */

import type {
  FeatureFlag,
  FeatureCategory,
} from './types';

/**
 * Default feature flag definitions for PersonalLog
 */
export const DEFAULT_FEATURES: FeatureFlag[] = [
  // ============================================================
  // AI FEATURES
  // ============================================================

  {
    id: 'ai.local_models',
    name: 'Local AI Models',
    description: 'Support for running AI models locally via Ollama',
    category: 'ai' as FeatureCategory,
    state: 'enabled',
    minHardwareScore: 30,
    userOverridable: true,
    experimental: false,
    tags: ['ai', 'local', 'ollama', 'privacy'],
    dependencies: [],
    performanceImpact: 70,
    minRAM: 8,
    minCores: 4,
  },
  {
    id: 'ai.streaming_responses',
    name: 'Streaming AI Responses',
    description: 'Stream AI responses token-by-token for better UX',
    category: 'ai' as FeatureCategory,
    state: 'enabled',
    minHardwareScore: 20,
    userOverridable: true,
    experimental: false,
    tags: ['ai', 'streaming', 'ux'],
    dependencies: [],
    performanceImpact: 10,
  },
  {
    id: 'ai.parallel_processing',
    name: 'Parallel AI Processing',
    description: 'Process multiple AI requests simultaneously',
    category: 'ai' as FeatureCategory,
    state: 'enabled',
    minHardwareScore: 50,
    userOverridable: true,
    experimental: false,
    tags: ['ai', 'performance', 'parallel'],
    dependencies: ['ai.streaming_responses'],
    performanceImpact: 40,
    minRAM: 16,
    minCores: 8,
  },
  {
    id: 'ai.voice_input',
    name: 'Voice Input',
    description: 'Voice-to-text input for AI conversations',
    category: 'ai' as FeatureCategory,
    state: 'enabled',
    minHardwareScore: 40,
    userOverridable: true,
    experimental: false,
    tags: ['ai', 'voice', 'input'],
    dependencies: [],
    performanceImpact: 30,
    minRAM: 4,
  },
  {
    id: 'ai.multimodal',
    name: 'Multimodal AI',
    description: 'Process images, audio, and video in AI conversations',
    category: 'ai' as FeatureCategory,
    state: 'enabled',
    minHardwareScore: 60,
    userOverridable: true,
    experimental: true,
    tags: ['ai', 'multimodal', 'experimental'],
    dependencies: ['ai.local_models'],
    performanceImpact: 80,
    minRAM: 16,
    requiresGPU: true,
  },

  // ============================================================
  // UI FEATURES
  // ============================================================

  {
    id: 'ui.virtual_scrolling',
    name: 'Virtual Scrolling',
    description: 'Virtual scrolling for long conversations',
    category: 'ui' as FeatureCategory,
    state: 'enabled',
    minHardwareScore: 30,
    userOverridable: true,
    experimental: false,
    tags: ['ui', 'performance', 'scrolling'],
    dependencies: [],
    performanceImpact: 20,
  },
  {
    id: 'ui.animations',
    name: 'UI Animations',
    description: 'Smooth animations and transitions',
    category: 'ui' as FeatureCategory,
    state: 'enabled',
    minHardwareScore: 40,
    userOverridable: true,
    experimental: false,
    tags: ['ui', 'animations', 'ux'],
    dependencies: [],
    performanceImpact: 15,
  },
  {
    id: 'ui.dark_mode',
    name: 'Dark Mode',
    description: 'Dark theme support',
    category: 'ui' as FeatureCategory,
    state: 'enabled',
    minHardwareScore: 0,
    userOverridable: true,
    experimental: false,
    tags: ['ui', 'theme', 'dark'],
    dependencies: [],
    performanceImpact: 0,
  },
  {
    id: 'ui.compact_mode',
    name: 'Compact Mode',
    description: 'Compact UI for small screens',
    category: 'ui' as FeatureCategory,
    state: 'enabled',
    minHardwareScore: 0,
    userOverridable: true,
    experimental: false,
    tags: ['ui', 'compact', 'mobile'],
    dependencies: [],
    performanceImpact: 0,
  },
  {
    id: 'ui.sidebar',
    name: 'Sidebar Navigation',
    description: 'Collapsible sidebar for navigation',
    category: 'ui' as FeatureCategory,
    state: 'enabled',
    minHardwareScore: 0,
    userOverridable: true,
    experimental: false,
    tags: ['ui', 'sidebar', 'navigation'],
    dependencies: [],
    performanceImpact: 0,
  },
  {
    id: 'ui.keyboard_shortcuts',
    name: 'Keyboard Shortcuts',
    description: 'Keyboard shortcuts for common actions',
    category: 'ui' as FeatureCategory,
    state: 'enabled',
    minHardwareScore: 0,
    userOverridable: true,
    experimental: false,
    tags: ['ui', 'keyboard', 'shortcuts'],
    dependencies: [],
    performanceImpact: 0,
  },

  // ============================================================
  // KNOWLEDGE FEATURES
  // ============================================================

  {
    id: 'knowledge.vector_search',
    name: 'Vector Search',
    description: 'Semantic search in knowledge base',
    category: 'knowledge' as FeatureCategory,
    state: 'enabled',
    minHardwareScore: 40,
    userOverridable: true,
    experimental: false,
    tags: ['knowledge', 'search', 'vector'],
    dependencies: [],
    performanceImpact: 50,
    minRAM: 8,
  },
  {
    id: 'knowledge.hybrid_search',
    name: 'Hybrid Search',
    description: 'Combined vector and keyword search',
    category: 'knowledge' as FeatureCategory,
    state: 'enabled',
    minHardwareScore: 50,
    userOverridable: true,
    experimental: false,
    tags: ['knowledge', 'search', 'hybrid'],
    dependencies: ['knowledge.vector_search'],
    performanceImpact: 60,
    minRAM: 8,
  },
  {
    id: 'knowledge.embeddings_cache',
    name: 'Embeddings Cache',
    description: 'Cache embeddings for faster search',
    category: 'knowledge' as FeatureCategory,
    state: 'enabled',
    minHardwareScore: 30,
    userOverridable: true,
    experimental: false,
    tags: ['knowledge', 'cache', 'performance'],
    dependencies: ['knowledge.vector_search'],
    performanceImpact: 20,
    minRAM: 4,
  },
  {
    id: 'knowledge.checkpoints',
    name: 'Knowledge Checkpoints',
    description: 'Version control for knowledge base',
    category: 'knowledge' as FeatureCategory,
    state: 'enabled',
    minHardwareScore: 20,
    userOverridable: true,
    experimental: false,
    tags: ['knowledge', 'versioning', 'checkpoints'],
    dependencies: [],
    performanceImpact: 10,
  },
  {
    id: 'knowledge.batch_import',
    name: 'Batch Import',
    description: 'Import multiple files at once',
    category: 'knowledge' as FeatureCategory,
    state: 'enabled',
    minHardwareScore: 30,
    userOverridable: true,
    experimental: false,
    tags: ['knowledge', 'import', 'batch'],
    dependencies: [],
    performanceImpact: 30,
    minRAM: 4,
  },

  // ============================================================
  // MEDIA FEATURES
  // ============================================================

  {
    id: 'media.image_analysis',
    name: 'Image Analysis',
    description: 'Analyze images in conversations',
    category: 'media' as FeatureCategory,
    state: 'enabled',
    minHardwareScore: 50,
    userOverridable: true,
    experimental: false,
    tags: ['media', 'image', 'analysis'],
    dependencies: ['ai.multimodal'],
    performanceImpact: 60,
    minRAM: 8,
    requiresGPU: true,
  },
  {
    id: 'media.audio_transcription',
    name: 'Audio Transcription',
    description: 'Transcribe audio messages',
    category: 'media' as FeatureCategory,
    state: 'enabled',
    minHardwareScore: 40,
    userOverridable: true,
    experimental: false,
    tags: ['media', 'audio', 'transcription'],
    dependencies: ['ai.voice_input'],
    performanceImpact: 50,
    minRAM: 4,
  },
  {
    id: 'media.video_thumbnail',
    name: 'Video Thumbnails',
    description: 'Generate thumbnails for video files',
    category: 'media' as FeatureCategory,
    state: 'enabled',
    minHardwareScore: 30,
    userOverridable: true,
    experimental: false,
    tags: ['media', 'video', 'thumbnails'],
    dependencies: [],
    performanceImpact: 20,
  },
  {
    id: 'media.compression',
    name: 'Media Compression',
    description: 'Compress media files before storage',
    category: 'media' as FeatureCategory,
    state: 'enabled',
    minHardwareScore: 40,
    userOverridable: true,
    experimental: false,
    tags: ['media', 'compression', 'storage'],
    dependencies: [],
    performanceImpact: 40,
    minRAM: 4,
  },

  // ============================================================
  // ADVANCED FEATURES
  // ============================================================

  {
    id: 'advanced.offline_mode',
    name: 'Offline Mode',
    description: 'Work offline with local data',
    category: 'advanced' as FeatureCategory,
    state: 'enabled',
    minHardwareScore: 20,
    userOverridable: true,
    experimental: false,
    tags: ['advanced', 'offline', 'pwa'],
    dependencies: [],
    performanceImpact: 0,
  },
  {
    id: 'advanced.background_sync',
    name: 'Background Sync',
    description: 'Sync data in the background',
    category: 'advanced' as FeatureCategory,
    state: 'enabled',
    minHardwareScore: 30,
    userOverridable: true,
    experimental: false,
    tags: ['advanced', 'sync', 'background'],
    dependencies: ['advanced.offline_mode'],
    performanceImpact: 20,
  },
  {
    id: 'advanced.encryption',
    name: 'Encryption at Rest',
    description: 'Encrypt stored data',
    category: 'advanced' as FeatureCategory,
    state: 'enabled',
    minHardwareScore: 40,
    userOverridable: true,
    experimental: false,
    tags: ['advanced', 'encryption', 'security'],
    dependencies: [],
    performanceImpact: 30,
    minRAM: 4,
  },
  {
    id: 'advanced.analytics',
    name: 'Usage Analytics',
    description: 'Track usage analytics locally',
    category: 'advanced' as FeatureCategory,
    state: 'enabled',
    minHardwareScore: 20,
    userOverridable: true,
    experimental: false,
    tags: ['advanced', 'analytics', 'privacy'],
    dependencies: [],
    performanceImpact: 10,
  },
  {
    id: 'advanced.experiments',
    name: 'A/B Testing',
    description: 'Participate in A/B experiments',
    category: 'advanced' as FeatureCategory,
    state: 'enabled',
    minHardwareScore: 20,
    userOverridable: true,
    experimental: false,
    tags: ['advanced', 'experiments', 'testing'],
    dependencies: ['advanced.analytics'],
    performanceImpact: 10,
  },
];
