/**
 * Markdown Converter
 *
 * Converts PersonalLog data to human-readable Markdown format.
 * Ideal for documentation, sharing, and archiving.
 */

import { ExportOptions, ExportStats } from '../types'
import { listConversations, getMessages } from '@/lib/storage/conversation-store'
import { getVectorStore } from '@/lib/knowledge/vector-store'
import { listContacts } from '@/lib/wizard/model-store'

export interface MarkdownOptions {
  includeMetadata: boolean
  includeTOC: boolean
  messageFormat: 'chat' | 'log' | 'narrative'
  codeBlocks: boolean
}

export class MarkdownConverter {
  /**
   * Export data to Markdown format
   */
  async exportData(options: ExportOptions, mdOptions: Partial<MarkdownOptions> = {}): Promise<{
    data: Blob
    stats: ExportStats
  }> {
    const startTime = Date.now()
    const finalOptions: MarkdownOptions = {
      includeMetadata: mdOptions.includeMetadata ?? true,
      includeTOC: mdOptions.includeTOC ?? true,
      messageFormat: mdOptions.messageFormat ?? 'chat',
      codeBlocks: mdOptions.codeBlocks ?? true,
    }

    let markdown = ''
    let stats: ExportStats = {
      conversations: 0,
      messages: 0,
      knowledgeEntries: 0,
      contacts: 0,
      totalSize: 0,
      duration: 0,
    }

    // Add header
    markdown += this.generateHeader(options)

    // Add table of contents
    if (finalOptions.includeTOC) {
      markdown += this.generateTOC(options)
    }

    // Export based on scope
    if (options.scope === 'all' || options.scope === 'conversations') {
      const { content, stats: convStats } = await this.exportConversations(options.dateRange, finalOptions)
      markdown += content
      stats.conversations = convStats.conversations
      stats.messages = convStats.messages
    }

    if (options.scope === 'all' || options.scope === 'knowledge') {
      const { content, stats: knowledgeStats } = await this.exportKnowledge(options.dateRange)
      markdown += content
      stats.knowledgeEntries = knowledgeStats.entries
    }

    if (options.scope === 'all' || options.scope === 'contacts') {
      const { content, stats: contactStats } = await this.exportContacts()
      markdown += content
      stats.contacts = contactStats.contacts
    }

    // Add footer
    markdown += this.generateFooter()

    // Create blob
    const encoder = new TextEncoder()
    const bytes = encoder.encode(markdown)
    stats.totalSize = bytes.length
    stats.duration = Date.now() - startTime

    const blob = new Blob([bytes], { type: 'text/markdown' })

    return { data: blob, stats }
  }

  /**
   * Generate document header
   */
  private generateHeader(options: ExportOptions): string {
    const date = new Date().toLocaleDateString()
    return `# PersonalLog Export

**Export Date:** ${date}
**Scope:** ${options.scope}

---

`
  }

  /**
   * Generate table of contents
   */
  private generateTOC(options: ExportOptions): string {
    let toc = '## Table of Contents\n\n'

    if (options.scope === 'all' || options.scope === 'conversations') {
      toc += '- [Conversations](#conversations)\n'
    }

    if (options.scope === 'all' || options.scope === 'knowledge') {
      toc += '- [Knowledge Base](#knowledge-base)\n'
    }

    if (options.scope === 'all' || options.scope === 'contacts') {
      toc += '- [AI Contacts](#ai-contacts)\n'
    }

    return toc + '\n---\n\n'
  }

  /**
   * Generate document footer
   */
  private generateFooter(): string {
    return `\n---\n\n*Generated by PersonalLog v2.0.0*\n`
  }

  /**
   * Export conversations to Markdown
   */
  private async exportConversations(
    dateRange: { start: Date; end: Date } | undefined,
    options: MarkdownOptions
  ): Promise<{ content: string; stats: { conversations: number; messages: number } }> {
    const conversations = await listConversations({ includeArchived: true })
    let markdown = '## Conversations\n\n'
    let messageCount = 0

    for (const conv of conversations) {
      // Apply date range filter
      if (dateRange) {
        const convDate = new Date(conv.createdAt)
        if (convDate < dateRange.start || convDate > dateRange.end) {
          continue
        }
      }

      // Get messages
      const messages = await getMessages(conv.id)
      messageCount += messages.length

      // Add conversation header
      markdown += `### ${this.escapeMarkdown(conv.title)}\n\n`

      if (options.includeMetadata) {
        markdown += `**Created:** ${new Date(conv.createdAt).toLocaleString()}\n`
        markdown += `**Updated:** ${new Date(conv.updatedAt).toLocaleString()}\n`
        markdown += `**Type:** ${conv.type}\n`
        markdown += `**Messages:** ${messages.length}\n\n`
      }

      // Add messages
      if (options.messageFormat === 'chat') {
        markdown += this.formatMessagesAsChat(messages, options)
      } else if (options.messageFormat === 'log') {
        markdown += this.formatMessagesAsLog(messages, options)
      } else {
        markdown += this.formatMessagesAsNarrative(messages, options)
      }

      markdown += '\n---\n\n'
    }

    return {
      content: markdown,
      stats: { conversations: conversations.length, messages: messageCount },
    }
  }

  /**
   * Format messages as chat (back-and-forth)
   */
  private formatMessagesAsChat(messages: any[], options: MarkdownOptions): string {
    let markdown = ''

    for (const msg of messages) {
      const author = this.getAuthorName(msg.author)
      markdown += `#### ${author}\n\n`

      if (msg.content.text) {
        if (options.codeBlocks && this.hasCode(msg.content.text)) {
          markdown += '```\n' + msg.content.text + '\n```\n\n'
        } else {
          markdown += this.escapeMarkdown(msg.content.text) + '\n\n'
        }
      }

      if (msg.content.media) {
        markdown += `[Media: ${msg.content.media.name}]\n\n`
      }

      if (options.includeMetadata && msg.timestamp) {
        markdown += `*${new Date(msg.timestamp).toLocaleString()}*\n\n`
      }
    }

    return markdown
  }

  /**
   * Format messages as log (chronological)
   */
  private formatMessagesAsLog(messages: any[], options: MarkdownOptions): string {
    let markdown = '| Time | Author | Message |\n|------|--------|----------|\n'

    for (const msg of messages) {
      const author = this.getAuthorName(msg.author)
      const time = msg.timestamp ? new Date(msg.timestamp).toLocaleTimeString() : ''
      const text = msg.content.text ? this.escapeMarkdown(msg.content.text).slice(0, 100) : '[Media]'

      markdown += `| ${time} | ${author} | ${text} |\n`
    }

    return markdown + '\n'
  }

  /**
   * Format messages as narrative (story-like)
   */
  private formatMessagesAsNarrative(messages: any[], options: MarkdownOptions): string {
    let markdown = ''

    for (const msg of messages) {
      const author = this.getAuthorName(msg.author)

      if (msg.content.text) {
        markdown += `> **${author}**: ${this.escapeMarkdown(msg.content.text)}\n\n`
      }

      if (msg.content.media) {
        markdown += `> *[Attached: ${msg.content.media.name}]*\n\n`
      }
    }

    return markdown
  }

  /**
   * Export knowledge entries to Markdown
   */
  private async exportKnowledge(
    dateRange: { start: Date; end: Date } | undefined
  ): Promise<{ content: string; stats: { entries: number } }> {
    const store = getVectorStore()
    await store.init()

    let entries = await store.getEntries()

    // Apply date range filter
    if (dateRange) {
      entries = entries.filter(e => {
        const entryDate = new Date(e.metadata.timestamp)
        return entryDate >= dateRange.start && entryDate <= dateRange.end
      })
    }

    let markdown = '## Knowledge Base\n\n'

    for (const entry of entries) {
      markdown += `### ${entry.type.toUpperCase()}: ${entry.sourceId}\n\n`

      if (entry.metadata.timestamp) {
        markdown += `**Date:** ${new Date(entry.metadata.timestamp).toLocaleString()}\n\n`
      }

      if (entry.editedContent) {
        markdown += `**Original:** ${entry.content}\n\n`
        markdown += `**Edited:** ${entry.editedContent}\n\n`
      } else {
        markdown += `${this.escapeMarkdown(entry.content)}\n\n`
      }

      if (entry.metadata.tags && entry.metadata.tags.length > 0) {
        markdown += `**Tags:** ${entry.metadata.tags.join(', ')}\n\n`
      }

      if (entry.metadata.starred) {
        markdown += '⭐ \n\n'
      }

      markdown += '---\n\n'
    }

    return {
      content: markdown,
      stats: { entries: entries.length },
    }
  }

  /**
   * Export AI contacts to Markdown
   */
  private async exportContacts(): Promise<{ content: string; stats: { contacts: number } }> {
    const contacts = await listContacts()
    let markdown = '## AI Contacts\n\n'

    for (const contact of contacts) {
      const c = contact as any
      markdown += `### ${this.escapeMarkdown(c.name || c.nickname || 'AI Contact')}\n\n`

      if (c.avatar) {
        markdown += `**Avatar:** ${c.avatar}\n\n`
      }

      markdown += `**Model:** ${c.config?.model || c.model || 'Unknown'}\n\n`
      markdown += `**Created:** ${new Date(contact.createdAt).toLocaleString()}\n\n`

      if (c.personality?.systemPrompt || c.systemPrompt) {
        markdown += `**System Prompt:**\n\n`
        markdown += '```\n'
        markdown += c.personality?.systemPrompt || c.systemPrompt || ''
        markdown += '\n```\n\n'
      }

      markdown += '---\n\n'
    }

    return {
      content: markdown,
      stats: { contacts: contacts.length },
    }
  }

  /**
   * Get display name for message author
   */
  private getAuthorName(author: any): string {
    if (author === 'user') return 'You'
    if (typeof author === 'object' && author.type === 'ai-contact') {
      return author.contactName || 'AI'
    }
    if (typeof author === 'object' && author.type === 'system') {
      return 'System'
    }
    return 'Unknown'
  }

  /**
   * Escape markdown special characters
   */
  private escapeMarkdown(text: string): string {
    // Don't escape code blocks
    return text
      .replace(/\\/g, '\\\\')
      .replace(/\*/g, '\\*')
      .replace(/_/g, '\\_')
      .replace(/\[/g, '\\[')
      .replace(/\]/g, '\\]')
      .replace(/\(/g, '\\(')
      .replace(/\)/g, '\\)')
      .replace(/#/g, '\\#')
      .replace(/\+/g, '\\+')
      .replace(/-/g, '\\-')
      .replace(/\./g, '\\.')
      .replace(/!/g, '\\!')
  }

  /**
   * Check if text contains code
   */
  private hasCode(text: string): boolean {
    return text.includes('```') || text.includes('`') || text.includes('function') || text.includes('const ')
  }
}
